### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by maruteaa**

### CODE REVIEW

**Review by AchmadAkif — CHANGES_REQUESTED** [review]
up tolong line 52, seng attribute step="0.01" diganti dadi step="1" wae

**Comment by maruteaa** [comment]
ra ben iso 4999.99 po :v

**Comment by AchmadAkif** [comment]
> ra ben iso 4999.99 po :v

jirlah, mana ada harga 4999,99 cu

**Comment by maruteaa** [comment]
sp tau penjual stress

**Pull request merged**
